### ISSUE TITLE
Can not open any video

### ISSUE THREAD

**Issue by d0niek** [FraserChapman/plugin.video.ng#1]
Hello,
when I want to try open any video I got an error in Kodi. In my log file I can see this:

```
2020-03-31 19:52:43.848 T:2402410704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.ValueError'>
Error Contents: time data 'Tue, 31 Mar 2020 17:50:09 GMT' does not match format '%a, %d %b %Y %H:%M:%S %Z'
Traceback (most recent call last):
File "/home/pi/.kodi/addons/plugin.video.ng/main.py", line 5, in <module>
plugin.run()
File "/home/pi/.kodi/addons/plugin.video.ng/resources/lib/plugin.py", line 275, in run
plugin.run()
File "/home/pi/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
self._dispatch(self.path)
File "/home/pi/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
view_func(**kwargs)
File "/home/pi/.kodi/addons/plugin.video.ng/resources/lib/plugin.py", line 212, in play_film
soup = ngs.get_html(url)
File "/home/pi/.kodi/addons/plugin.video.ng/resources/lib/search.py", line 133, in get_html
c.set(uri, r.content, r.headers)
File "/home/pi/.kodi/addons/script.module.cache/lib/cache.py", line 199, in set
httpdate_to_datetime(headers.get("date")),
File "/home/pi/.kodi/addons/script.module.cache/lib/cache.py", line 38, in httpdate_to_datetime
return datetime(*(time.strptime(input_date, HTTP_DATE_FORMAT)[0:6]))
File "/usr/lib/python2.7/_strptime.py", line 478, in _strptime_time
return _strptime(data_string, format)[0]
File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
(data_string, format))
ValueError: time data 'Tue, 31 Mar 2020 17:50:09 GMT' does not match format '%a, %d %b %Y %H:%M:%S %Z'
-->End of Python script error report<--
```

I don't if I have to old or to newest packages?

My kodi version:

```
$ kodi --version
18.6 Git:20200310-283bece277 Media Center Kodi
Copyright (C) 2005-2019 Team Kodi - http://kodi.tv
```

My python version:

```
$ python2.7 -V
Python 2.7.16
```

Do you need any more information?

**Comment by FraserChapman** [comment]
@d0niek sorry don't know how I missed this! It is because NG have changed how they stream content - will have a look to see if it can be fixed. Thanks for raising this!
